### ISSUE TITLE
error on install 

### ISSUE THREAD

**Issue by sull** [kadena-io/pact-todomvc#1]
Getting this error on OSX brew install:

Error: No available formula with the name "pact" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/impactor
To install it, run:
  brew install Caskroom/cask/impactor
sull:~ sulleleven$ brew install Caskroom/cask/impactor
==> brew cask install Caskroom/cask/impactor
Warning: A Cask for impactor is already installed.

To re-install impactor, run:
  brew cask reinstall impactor

**Comment by buckie** [comment]
Sorry, I pushed this to O/S about half a day prior to pact v2.1.0's release & brew integration being finished. I've updated the docs to reflect the right install command and updated the repo to work with the latest version of pact. Please let me know if you have any trouble.
